# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "json", "~> 2.6"

gem "net-http", "~> 0.2.0"

gem "colorize", "~> 0.8.1"

gem "tty-table", "~> 0.12.0"

gem "tty-prompt", "~> 0.23.1"
